.TH Shexy 1
.SH NAME
Shexy
.SH SYNOPSIS
.B shexy [OPTIONS]... [FILE]
.SH DESCRIPTION
Shexy is a hex-dump viewer witten in C.
.SH OPTIONS
.B \-c 
Display data with color.
.TP
.B \-f
Set the output format (binary, octal, decimar or hexadecimal).
.TP
.B \-l
Number of colums per line.
.TP
.B \-n
Number of bytes to read.
.TP
.B \-s
Number of bytes to skip.
.SH USAGE
.SH SEE ALSO
.SH BUGS
.SH AUTHOR
